apiVersion: policies.kyverno.io/v1alpha1
kind: ValidatingPolicy
metadata:
  name: require-ingress-https
  annotations:
    policies.kyverno.io/title: Require Ingress HTTPS in ValidatingPolicy
    policies.kyverno.io/category: Other in Vpol 
    policies.kyverno.io/severity: medium
    kyverno.io/kyverno-version: 1.14.0
    kyverno.io/kubernetes-version: "1.30"
    policies.kyverno.io/subject: Ingress
    policies.kyverno.io/description: >-
      Ingress resources should only allow secure traffic by disabling
      HTTP and therefore only allowing HTTPS. This policy requires that all
      Ingress resources set the annotation `kubernetes.io/ingress.allow-http` to
      `"false"` and specify TLS in the spec.
spec:
  evaluation:
    background:
      enabled: true 
  validationActions: 
    - Audit
  matchConstraints:
    resourceRules:
    - apiGroups:   ["networking.k8s.io"]
      apiVersions: ["v1"]
      operations:  ["CREATE", "UPDATE"]
      resources:   ["ingresses"]
  validations:
    - expression: >-
        object.metadata.?annotations[?'kubernetes.io/ingress.allow-http'].orValue('default') == 'false'
      message: "The kubernetes.io/ingress.allow-http annotation must be set to false."
    - expression: "has(object.spec.tls)"
      message: "TLS must be defined."

