name: concatenate-configmaps
version: 1.0.0
displayName: Concatenate ConfigMaps
createdAt: "2023-04-10T20:30:03.000Z"
description: >-
  In some cases, an update to an existing resource should have downstream effects on a different resource in another Namespace. Rather than overwriting the target, the current state of the source can be concatenated to the target. This policy, triggered by an update to a source ConfigMap, concatenates that value of a target ConfigMap in a different Namespace.
install: |-
  ```shell
  kubectl apply -f https://raw.githubusercontent.com/kyverno/policies/main/other/concatenate-configmaps/concatenate-configmaps.yaml
  ```
keywords:
  - kyverno
  - other
readme: |
  In some cases, an update to an existing resource should have downstream effects on a different resource in another Namespace. Rather than overwriting the target, the current state of the source can be concatenated to the target. This policy, triggered by an update to a source ConfigMap, concatenates that value of a target ConfigMap in a different Namespace.
  
  Refer to the documentation for more details on Kyverno annotations: https://artifacthub.io/docs/topics/annotations/kyverno/
annotations:
  kyverno/category: "other"
  kyverno/kubernetesVersion: "1.23"
  kyverno/subject: "ConfigMap"
digest: dba13356d5eb4dec2a3dad8432774239b9f0cd4cb17d968d941701e8a7a81cc5
