name: limit-configmap-for-sa
version: 1.0.0
displayName: Limit ConfigMap to ServiceAccounts for a User
createdAt: "2023-04-10T20:30:04.000Z"
description: >-
  This policy shows how to restrict certain operations on specific ConfigMaps by ServiceAccounts.
install: |-
  ```shell
  kubectl apply -f https://raw.githubusercontent.com/kyverno/policies/main/other/limit-configmap-for-sa/limit-configmap-for-sa.yaml
  ```
keywords:
  - kyverno
  - Other
readme: |
  This policy shows how to restrict certain operations on specific ConfigMaps by ServiceAccounts.
  
  Refer to the documentation for more details on Kyverno annotations: https://artifacthub.io/docs/topics/annotations/kyverno/
annotations:
  kyverno/category: "Other"
  kyverno/kubernetesVersion: "1.20-1.23"
  kyverno/subject: "ConfigMap, ServiceAccount"
digest: d05b789387da92170215cd0a37a17b95b071c9012fe9f4104bb94fc6da36a63e
